#!/usr/bin/env sh

SCRIPT_DIR=`dirname $0`
RELEASE_PATH=`cd $SCRIPT_DIR/../ && pwd`

exec env MIX_HOME=$RELEASE_PATH/.mix HEX_HOME=$RELEASE_PATH/.hex ERL_PATH=$RELEASE_PATH/binstubs/erl $RELEASE_PATH/elixir/bin/elixir "$@"
