#!/usr/bin/env sh

SCRIPT_DIR=`dirname $0`
RELEASE_PATH=`cd $SCRIPT_DIR/../ && pwd`

env MIX_HOME=$RELEASE_PATH/.mix HEX_HOME=$RELEASE_PATH/.hex $RELEASE_PATH/binstubs/erl -- -pa $RELEASE_PATH/elixir/lib/*/ebin -elixir ansi_enabled true -user Elixir.IEx.CLI -extra --no-halt +iex "$@"
